### PR TITLE
2015 q1

### PR DESCRIPTION
**Pull request by sofer**
@iteles first quarter summary is ready. Perhaps we should give members a chance to scrutinise it before we push to master. 

The numbers come straight from Xero.

### CODE REVIEW

**Comment by iteles** [comment]
@sofer Reckon you should present these in the business meeting projected on the wall for example?
It needs to be tempered with the current status of funds.

Also, that £4k disappeared quickly. If we had creditors (which we certainly did, at least from the indiegogo campaign), we should add them in.

**Comment by sofer** [comment]
@iteles very good point about creditors. I'll take a look at that. We have some expenses unclaimed, too. Do you have any to add?

p.s. which £4k are you referring to?

**Comment by sofer** [comment]
Have added £1,750 of Indiegogo liabilities (£1,300 for you and Nelson + £450 of workshops for schools).

**Comment by iteles** [comment]
@sofer Thanks for putting these together :blush:
@nelsonic Given your accountancy background, any thoughts on how we should improve these?

**Comment by sofer** [comment]
@iteles  I have made a couple of small edits: added a "directors' remuneration row and pointed out that contributions from members were a significant source of net income.

**Comment by iteles** [comment]
@sofer :+1: We should publish these very soon! 
My only question is: it looks like we have money left over at the end of the quarter even once creditors are taken into account (though it never felt like it!) - was this basically available to pay the following month's rent?

**Comment by sofer** [comment]
@iteles exactly. £2,200 went on rent on the 1st of the month.

**Comment by iteles** [comment]
Perfect. I'd add a note at the bottom to that effect and we can merge this after the business meeting :blush:

**Comment by sofer** [comment]
@iteles done.

**Pull request merged**
